<Project>
  <PropertyGroup>
    <MSBuildProjectExtensionsPath>$(MSBuildThisFileDirectory)..\artifacts\obj\$(MSBuildProjectName)\</MSBuildProjectExtensionsPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)..\artifacts\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory)..\artifacts\bin\$(MSBuildProjectName)\</BaseOutputPath>
  </PropertyGroup>
</Project>
